name: Deploy React build to Raspberry Pi via Tailscale

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.16.0

      - name: Install dependencies
        working-directory: dashboard/frontend
        run: npm install

      - name: Build React app
        working-directory: dashboard/frontend
        run: CI='' npm run build

      - name: Start Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Remove old build directory from Raspberry Pi
        run: |
          ssh -o StrictHostKeyChecking=no root@raspberrypi "rm -rf /opt/Hackaburg25/dashboard/frontend/build/"

      - name: Copy new build folder to Raspberry Pi
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" dashboard/frontend/build/ root@raspberrypi:/opt/Hackaburg25/dashboard/frontend/frontend/build/
